{-# LANGUAGE TemplateHaskell #-}
module UnitTest.ResponseParse.TagResponse where


import Data.Aeson (Value)
import Data.Yaml.TH (decodeFile)
import Language.Haskell.TH (liftCode)

import Test.Tasty as Tasty
import Web.Facebook.Messenger

import UnitTest.Internal

------------------
-- TAG RESPONSE --
------------------

tagResponseVal :: Value
tagResponseVal = $$(liftCode $ decodeFile "test/json/response/tag_response.json")

tagResponseTest :: TestTree
tagResponseTest = parseTest "Tag Response" tagResponseVal
                $ DataResponse [ TagElement SHIPPING_UPDATE "The shipping_update tag may only be used to provide a shipping status notification for a product that has already been purchased. For example, when the product is shipped, in-transit, delivered, or delayed. This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements)."
                               , TagElement RESERVATION_UPDATE "The reservation_update tag may only be used to confirm updates to an existing reservation. For example, when there is a change in itinerary, location, or a cancellation (such as when a hotel booking is canceled, a car rental pick-up time changes, or a room upgrade is confirmed). This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements)."
                               , TagElement ISSUE_RESOLUTION "The issue_resolution tag may only be used to respond to a customer service issue surfaced in a Messenger conversation after a transaction has taken place. This tag is intended for use cases where the business requires more than 24 hours to resolve an issue and needs to give someone a status update and/or gather additional information. This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements, nor can businesses use the tag to proactively message people to solicit feedback)."
                               , TagElement APPOINTMENT_UPDATE "The appointment_update tag may only be used to provide updates about an existing appointment. For example, when there is a change in time, a location update or a cancellation (such as when a spa treatment is canceled, a real estate agent needs to meet you at a new location or a dental office proposes a new appointment time). This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements)."
                               , TagElement GAME_EVENT "The game_event tag may only be used to provide an update on user progression, a global event in a game or a live sporting event. For example, when a person’s crops are ready to be collected, their building is finished, their daily tournament is about to start or their favorite soccer team is about to play. This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements)."
                               , TagElement TRANSPORTATION_UPDATE "The transportation_update tag may only be used to confirm updates to an existing reservation. For example, when there is a change in status of any flight, train or ferry reservation (such as “ride canceled”, “trip started” or “ferry arrived”). This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements)."
                               , TagElement FEATURE_FUNCTIONALITY_UPDATE "The feature_functionality_update tag may only be used to provide an update on new features or functionality that become available in a bot. For example, announcing the ability to talk to a live agent in a bot, or that the bot has a new skill. This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements)."
                               , TagElement TICKET_UPDATE "The ticket_update tag may only be used to notify the message recipient of updates or reminders pertaining to an event for which the person has already confirmed attendance. For example, when you want to send a message about a change in time, a location update, a cancellation or a reminder for an upcoming event (such as when a concert is canceled, the venue has changed or a refund opportunity is available). This tag cannot be used for use cases beyond those listed above or for promotional content (ex: daily deals, coupons and discounts, or sale announcements)."
                               , TagElement ACCOUNT_UPDATE "The ACCOUNT_UPDATE tag may only be used to confirm updates to a user's account setting.  For example, when there is a change in account settings and preferences of a user profile, notification of a password change, or membership expiration.  This tag cannot be used for use cases beyond those listed above or for promotional content (ex: promotion for signups, new account creations, or deals to extend subscriptions)."
                               , TagElement PAYMENT_UPDATE "The PAYMENT_UPDATE tag may be used to provide payment updates to existing transactions.  For example, it can be used to send a receipt, out-of-stock, auction ended, refund, or a status change in an existing purchase transaction.  This tag cannot be used for use cases beyond those listed above or for promotional content (ex: any cross-sell / up-sell promotions, coupons, or deals to extend subscriptions)."
                               , TagElement PERSONAL_FINANCE_UPDATE "The PERSONAL_FINANCE_UPDATE tag may be used to confirm a user's financial activity.  For example, it can be used to send notifications on bill pay reminders, scheduled payments, receipts of payment, transfer of funds, or other transactional activities in financial services.  This tag cannot be used for use cases beyond those listed above or for promotional content (ex: promotion for signups, or offers such as free trials for any financial products)."
                               , TagElement PAIRING_UPDATE "The pairing_update tag can be used to notify the message recipient that a pairing has been identified based on the recipient's prior request. Examples: Match has been confirmed in a dating app. User has confirmed an open parking spot for someone who previously requested one."
                               , TagElement APPLICATION_UPDATE "The application_update tag can be used to notify the message recipient of an update on the status of their application. Examples: Application is being reviewed. Application has been rejected."
                               , TagElement CONFIRMED_EVENT_REMINDER "The confirmed_event_reminder tag can be used to send the message recipient reminders of a scheduled event for which a person is going to attend. Examples: Upcoming classes or events that a person has signed up for. Confirmation of attendance to an accepted event or appointment."
                               , TagElement COMMUNITY_ALERT "The community_alert tag can be used to notify the message recipient of utility alerts, or safety checks in your community. Examples: Request a safety check. Notify of an emergency or utility alerts."
                               , TagElement NON_PROMOTIONAL_SUBSCRIPTION "The non_promotional_subscription tag can be used to send non-promotional messages under the News, Productivity, and Personal Trackers categories described in the Messenger Platform's subscription messaging policy. You can apply for access to use this tag under the Page Settings > Messenger Platform. Use Cases: News. Productivity. Personal Trackers."
                               ]
